# Recommended wrangler.toml format
name = "bland" # Or your preferred descriptive name
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]


# --- Build configuration IS REQUIRED for TypeScript ---
[build]
command = "npm run build" # Assumes 'npm run build' runs 'tsc' in your package.json
# watch_dir = "src" # Optional: helps wrangler dev rebuild faster

# --- Optional: Enhanced Observability ---
[observability]
enabled = true

# --- Make sure your package.json has a "build" script, e.g., "build": "tsc" ---

# --- Add secrets using `wrangler secret put SECRET_NAME` ---
# --- Do NOT list secrets here ---

# --- Bindings like KV, D1, etc., would go here if needed ---
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "..."